#!/usr/bin/env ruby
require "bundler/setup"
require "devtools"
require "runtest"
require "find"

module RunTest
  files = { jest: [], mocha: [], diff: [] }

  RunTest::OptParse.parse(ARGV)

  if Options.changed
    files[:diff] = %x(#{Options.commands.diff}).split("\n").map { |f| "#{File.basename(f, ".js")}-spec" }
    DevTools::Utils.die "No modified spec files found" if files[:diff].empty? && ARGV.empty?
  end

  if !files[:diff].empty? || ARGV.length > 0
    [files[:diff], ARGV].flatten.compact.each do |arg|
      found = false

      puts "looking for tests matching \"#{arg}\"" if Options.verbose > 1

      Find.find(Options.basedir) do |path|
        if FileTest.directory?(path)
          if File.basename(path)[0] == ?.
            Find.prune # Don't look any further into this directory.
          else
            next
          end
        else
          if path =~ /__(spec|test)s?__\/.*#{arg}.*/
            files[$1 =~ /test/ ? :jest : :mocha].push path
            found = true
          end
        end
      end

      puts "No tests found matching #{arg}" unless found
    end

    [:jest, :mocha].each do |suite|
      next unless Options[suite]

      if files[suite].length > 0
        if Options.verbose > 2
          puts "\nRunning #{suite.capitalize} on..."
          puts "    #{files[suite].join("\n    ")}\n\n"
        else
          puts "\nRunning #{files[suite].length} #{suite.capitalize} test(s)" if Options.verbose > 0
        end

        system "#{Options.commands[suite]} #{files[suite].join(" ")}"
      end
    end

    exit files[:jest].length > 0 || files[:mocha].length > 0 ? 0 : 1

  else
    [:jest, :mocha].each do |suite|
      if Options[suite]
        puts "Running full #{suite.capitalize} test suite" if Options.verbose > 0
        system "npm run test:#{suite}"
      end
    end
  end
end # module RunTest
